"""Audit decomp/ for residue from the removed PE repackaging (MAINDOS_32BIT.EXE).

Flags:
  - PE-style address literals (0x004xxxxx / 0x005xxxxx)
  - symbols suffixed with a PE address (e.g. s_Foo_004995c8)
  - raw Ghidra names (DAT_00..., FUN_00...)
  - placeholder globals of the form `uint32_t g_X[16] = {0};`

Writes docs/tracking/pe_residue.md. Exit code 1 if any residue remains
(or if the count exceeds the ratchet in docs/tracking/pe_residue_baseline.txt).
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCAN_DIRS = ["decomp/src", "decomp/include"]
BASELINE = os.path.join(ROOT, "docs", "tracking", "pe_residue_baseline.txt")
REPORT = os.path.join(ROOT, "docs", "tracking", "pe_residue.md")

PATTERNS = [
    ("pe_literal", re.compile(r"\b0x00[45][0-9a-fA-F]{5}\b")),
    ("pe_symbol", re.compile(r"\b[A-Za-z_][A-Za-z_0-9]*_00[45][0-9a-fA-F]{5}\b")),
    ("ghidra_name", re.compile(r"\b(?:DAT|FUN)_[0-9a-fA-F]{8}\b")),
    ("placeholder_global", re.compile(r"^\s*uint32_t\s+g_\w+\[16\]\s*=\s*\{0\};")),
]


def scan():
    hits = []
    for d in SCAN_DIRS:
        for dirpath, _, files in os.walk(os.path.join(ROOT, d)):
            for name in files:
                if not name.endswith((".c", ".h")):
                    continue
                path = os.path.join(dirpath, name)
                rel = os.path.relpath(path, ROOT).replace("\\", "/")
                with open(path, "r", errors="replace") as f:
                    for lineno, line in enumerate(f, 1):
                        for kind, rx in PATTERNS:
                            m = rx.search(line)
                            if m:
                                hits.append((rel, lineno, kind, m.group(0) if kind != "placeholder_global" else line.strip()))
    return hits


def main():
    hits = scan()
    by_file = {}
    for h in hits:
        by_file.setdefault(h[0], []).append(h)

    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w") as f:
        f.write("# PE Residue Report\n\n")
        f.write("> Auto-generated by `tools/audit_pe_residue.py`. Goal: zero.\n\n")
        f.write("Total: **%d**\n\n| File | Count |\n| :--- | ---: |\n" % len(hits))
        for rel, items in sorted(by_file.items()):
            f.write("| `%s` | %d |\n" % (rel, len(items)))
        f.write("\n## Details\n\n")
        for rel, items in sorted(by_file.items()):
            f.write("### %s\n\n" % rel)
            for _, lineno, kind, text in items:
                f.write("- L%d `%s` %s\n" % (lineno, kind, text.replace("|", "\\|")))
            f.write("\n")

    print("PE residue: %d hit(s) in %d file(s)" % (len(hits), len(by_file)))
    for rel, items in sorted(by_file.items()):
        print("  %-28s %d" % (rel, len(items)))

    baseline = None
    if os.path.exists(BASELINE):
        with open(BASELINE) as f:
            baseline = int(f.read().strip() or "0")
    if "--update-baseline" in sys.argv:
        with open(BASELINE, "w") as f:
            f.write(str(len(hits)))
        print("Baseline set to %d" % len(hits))
        return 0
    if baseline is not None and len(hits) > baseline:
        print("[FAIL] residue increased: %d > baseline %d" % (len(hits), baseline))
        return 1
    return 0 if len(hits) == 0 or baseline is not None else 1


if __name__ == "__main__":
    sys.exit(main())
